# Using zsh
set-option -g default-shell /bin/zsh

# Colors
# set -g status-style bg="#013220"
set -g status-style bg="#1e0c25"
set -ag status-style fg="colour141"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Key bindings

## Prefix
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Sessions
bind S command-prompt -p "New Session:" "new-session -A -s '%%'"
bind K confirm kill-session

## Copy mode
unbind-key [
bind-key k copy-mode

## Vim style
set-window-option -g mode-keys vi
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -selection clipboard'
bind -T copy-mode-vi Y send-keys -X copy-pipe-and-cancel 'xclip -selection clipboard'
bind -T copy-mode-vi v send-keys -X begin-selection

bind p run "xclip -o -sel clip | tmux load-buffer - ; tmux paste-buffer"

bind r run "tmux source-file ~/.tmux.conf"

set-option -g history-limit 9000

set -g mouse on

## Rebinding to always create new window on current path by default
bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
