# Vim style
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -sel clip > /dev/null"
bind-key p run "xclip -o -sel clip | tmux load-buffer - ; tmux paste-buffer"

# Colors
set -g status-style bg=default

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Key bindings

unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

unbind-key [
bind-key k copy-mode

bind-key r source-file ~/.tmux.conf
